import Head from 'next/head'
import Image from 'next/image'
import Choose from '../components/Choose'
import Company from '../components/Company'
import Hero from '../components/Hero'
import Navbar from '../components/Navbar'
import Service from '../components/Service'
import Users from '../components/Users'




export default function Home() {
  return (
    <div >
      <Head>
        <title>GrowFy Marketing website Landing Page</title>
        <meta name="description" content="Generated by create next app" />
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@200;300;400;500;600;700;800;900&display=swap" rel="stylesheet"></link>
        <link rel="icon" href="/favicon.ico" />
      </Head>
  <Navbar/>
  <Hero/>
  <Company/>
  <Service/>
  <Choose/>
  <Users/>

    </div>
  )
}
